version: '3.8'

services:
  auth-client:
    image: yuriitsiurpita/auth-client:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - auth-server

  auth-server:
    image: yuriitsiurpita/auth-server:latest
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: mysql:8.0.32-debian
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth-app
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local