version: '3.8'

services:
  db:
    image: mysql:8.0.32-debian
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth-app
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local